const $ = <T extends Element>(id: string): T =>
  document.getElementById(id) as unknown as T;

export const dom = {
  mainLayout: $<HTMLElement>("mainLayout"),
  sprintSubHeader: $<HTMLElement>("sprintSubHeader"),
  sprintList: $<HTMLElement>("sprintList"),
  projectTodayInput: $<HTMLInputElement>("projectTodayInput"),
  newSprintBtn: $<HTMLButtonElement>("newSprintBtn"),
  resetSprintBtn: $<HTMLButtonElement>("resetSprintBtn"),
  deleteSprintBtn: $<HTMLButtonElement>("deleteSprintBtn"),
  sprintTitleText: $<HTMLElement>("sprintTitleText"),
  editSprintBtn: $<HTMLButtonElement>("editSprintBtn"),
  summaryDuration: $<HTMLElement>("summaryDuration"),
  efficiencyDisplay: $<HTMLElement>("efficiencyDisplay"),
  taskRows: $<HTMLTableSectionElement>("taskRows"),
  totalPoints: $<HTMLElement>("totalPoints"),
  remainingPoints: $<HTMLElement>("remainingPoints"),
  workingDays: $<HTMLElement>("workingDays"),
  doneTasks: $<HTMLElement>("doneTasks"),
  availableDays: $<HTMLElement>("availableDays"),
  availableDaysValue: $<HTMLElement>("availableDaysValue"),
  progressPercent: $<HTMLElement>("progressPercent"),
  progressBarFill: $<HTMLElement>("progressBarFill"),
  chart: $<SVGSVGElement>("burndownChart"),
  showDayNumbers: $<HTMLInputElement>("showDayNumbers"),
  exportCsvBtn: document.getElementById("exportCsvBtn") as HTMLButtonElement | null,
  exportBtn: $<HTMLButtonElement>("exportBtn"),
  importBtn: $<HTMLButtonElement>("importBtn"),
  importFile: $<HTMLInputElement>("importFile"),
  sprintModal: $<HTMLElement>("sprintModal"),
  modalTitle: $<HTMLElement>("modalTitle"),
  modalDescription: $<HTMLInputElement>("modalDescription"),
  modalStartDate: $<HTMLInputElement>("modalStartDate"),
  modalWorkingDays: $<HTMLElement>("modalWorkingDays"),
  modalManDays: $<HTMLElement>("modalManDays"),
  modalEndDate: $<HTMLInputElement>("modalEndDate"),
  modalDevelopers: $<HTMLInputElement>("modalDevelopers"),
  modalEfficiency: $<HTMLInputElement>("modalEfficiency"),
  modalError: $<HTMLElement>("modalError"),
  modalSave: $<HTMLButtonElement>("modalSave"),
  modalCancel: $<HTMLButtonElement>("modalCancel"),
  modalClose: $<HTMLButtonElement>("modalClose"),
  sprintItemTemplate: $<HTMLTemplateElement>("sprintItemTemplate"),
  taskRowTemplate: $<HTMLTemplateElement>("taskRowTemplate"),
  // Tabs
  tabSprint: $<HTMLButtonElement>("tabSprint"),
  tabBacklog: $<HTMLButtonElement>("tabBacklog"),
  sprintView: $<HTMLElement>("sprintView"),
  backlogView: $<HTMLElement>("backlogView"),
  // Sprint task card — add-by-ID
  addByIdInput: $<HTMLInputElement>("addByIdInput"),
  addByIdBtn: $<HTMLButtonElement>("addByIdBtn"),
  // Backlog panel (sprint view, drag-to-add)
  backlogPanel: $<HTMLElement>("backlogPanel"),
  backlogPanelToggle: $<HTMLButtonElement>("backlogPanelToggle"),
  backlogPanelRows: $<HTMLElement>("backlogPanelRows"),
  backlogPanelRowTemplate: $<HTMLTemplateElement>("backlogPanelRowTemplate"),
  // Backlog view
  backlogExpandAllBtn: $<HTMLButtonElement>("backlogExpandAllBtn"),
  backlogCollapseAllBtn: $<HTMLButtonElement>("backlogCollapseAllBtn"),
  backlogAddStoryBtn: $<HTMLButtonElement>("backlogAddStoryBtn"),
  backlogImportCsvBtn: $<HTMLButtonElement>("backlogImportCsvBtn"),
  backlogExportCsvBtn: $<HTMLButtonElement>("backlogExportCsvBtn"),
  backlogDeleteAllBtn: $<HTMLButtonElement>("backlogDeleteAllBtn"),
  backlogImportFile: $<HTMLInputElement>("backlogImportFile"),
  backlogTableBody: $<HTMLTableSectionElement>("backlogTableBody"),
  backlogStoryRowTemplate: $<HTMLTemplateElement>("backlogStoryRowTemplate"),
  backlogTaskRowTemplate: $<HTMLTemplateElement>("backlogTaskRowTemplate"),
  // Sprint Planning Modal
  sprintPlanModal: $<HTMLElement>("sprintPlanModal"),
  sprintPlanTitle: $<HTMLElement>("sprintPlanTitle"),
  sprintPlanClose: $<HTMLButtonElement>("sprintPlanClose"),
  sprintPlanDone: $<HTMLButtonElement>("sprintPlanDone"),
  planStatDuration: $<HTMLElement>("planStatDuration"),
  planStatWorkingDays: $<HTMLElement>("planStatWorkingDays"),
  planStatTotalPoints: $<HTMLElement>("planStatTotalPoints"),
  planStatAvailableDays: $<HTMLElement>("planStatAvailableDays"),
  planTaskRows: $<HTMLTableSectionElement>("planTaskRows"),
  planBacklogRows: $<HTMLElement>("planBacklogRows"),
  planTaskRowTemplate: $<HTMLTemplateElement>("planTaskRowTemplate"),
  // Delete Sprint confirm dialog
  confirmDeleteSprintModal: $<HTMLElement>("confirmDeleteSprintModal"),
  confirmDeleteSprintName: $<HTMLElement>("confirmDeleteSprintName"),
  confirmDeleteSprintCancel: $<HTMLButtonElement>("confirmDeleteSprintCancel"),
  confirmDeleteSprintConfirm: $<HTMLButtonElement>("confirmDeleteSprintConfirm"),
  // Reset Sprint confirm dialog
  confirmResetSprintModal: $<HTMLElement>("confirmResetSprintModal"),
  confirmResetSprintName: $<HTMLElement>("confirmResetSprintName"),
  confirmResetSprintCancel: $<HTMLButtonElement>("confirmResetSprintCancel"),
  confirmResetSprintConfirm: $<HTMLButtonElement>("confirmResetSprintConfirm"),
  // Backlog "Clear All" confirm dialog
  confirmDeleteBacklogModal: $<HTMLElement>("confirmDeleteBacklogModal"),
  confirmDeleteBacklogCancel: $<HTMLButtonElement>("confirmDeleteBacklogCancel"),
  confirmDeleteBacklogConfirm: $<HTMLButtonElement>("confirmDeleteBacklogConfirm"),
  // Task remove confirm dialog
  confirmRemoveTaskModal: $<HTMLElement>("confirmRemoveTaskModal"),
  confirmRemoveTaskName: $<HTMLElement>("confirmRemoveTaskName"),
  confirmRemoveTaskCancel: $<HTMLButtonElement>("confirmRemoveTaskCancel"),
  confirmRemoveTaskConfirm: $<HTMLButtonElement>("confirmRemoveTaskConfirm"),
  // Import confirm dialog (reusable)
  importConfirmModal: $<HTMLElement>("importConfirmModal"),
  importConfirmTitle: $<HTMLElement>("importConfirmTitle"),
  importConfirmMessage: $<HTMLElement>("importConfirmMessage"),
  importConfirmSubtext: $<HTMLElement>("importConfirmSubtext"),
  importConfirmCancel: $<HTMLButtonElement>("importConfirmCancel"),
  importConfirmOk: $<HTMLButtonElement>("importConfirmOk"),
  // Preferences modal
  settingsBtn: $<HTMLButtonElement>("settingsBtn"),
  preferencesModal: $<HTMLElement>("preferencesModal"),
  prefClose: $<HTMLButtonElement>("prefClose"),
  prefDone: $<HTMLButtonElement>("prefDone"),
  prefHolidayDate: $<HTMLInputElement>("prefHolidayDate"),
  prefHolidayName: $<HTMLInputElement>("prefHolidayName"),
  prefHolidayAddBtn: $<HTMLButtonElement>("prefHolidayAddBtn"),
  prefHolidayList: $<HTMLElement>("prefHolidayList"),
  prefWeekendDate: $<HTMLInputElement>("prefWeekendDate"),
  prefWeekendAddBtn: $<HTMLButtonElement>("prefWeekendAddBtn"),
  prefWeekendList: $<HTMLElement>("prefWeekendList"),
  // Members
  prefMemberName: $<HTMLInputElement>("prefMemberName"),
  prefMemberAddBtn: $<HTMLButtonElement>("prefMemberAddBtn"),
  prefMemberList: $<HTMLElement>("prefMemberList"),
};
