export const dom = {
  mainLayout: document.getElementById("mainLayout"),
  sprintSubHeader: document.getElementById("sprintSubHeader"),
  sprintList: document.getElementById("sprintList"),
  newSprintBtn: document.getElementById("newSprintBtn"),
  deleteSprintBtn: document.getElementById("deleteSprintBtn"),
  sprintTitleText: document.getElementById("sprintTitleText"),
  editSprintBtn: document.getElementById("editSprintBtn"),
  summaryDuration: document.getElementById("summaryDuration"),
  sprintToday: document.getElementById("sprintToday"),
  taskRows: document.getElementById("taskRows"),
  totalPoints: document.getElementById("totalPoints"),
  remainingPoints: document.getElementById("remainingPoints"),
  workingDays: document.getElementById("workingDays"),
  doneTasks: document.getElementById("doneTasks"),
  availableDays: document.getElementById("availableDays"),
  availableDaysValue: document.getElementById("availableDaysValue"),
  chart: document.getElementById("burndownChart"),
  showDayNumbers: document.getElementById("showDayNumbers"),
  exportCsvBtn: document.getElementById("exportCsvBtn"),
  exportBtn: document.getElementById("exportBtn"),
  importBtn: document.getElementById("importBtn"),
  importFile: document.getElementById("importFile"),
  sprintModal: document.getElementById("sprintModal"),
  modalTitle: document.getElementById("modalTitle"),
  modalDescription: document.getElementById("modalDescription"),
  modalStartDate: document.getElementById("modalStartDate"),
  modalWorkingDays: document.getElementById("modalWorkingDays"),
  modalEndDate: document.getElementById("modalEndDate"),
  modalDevelopers: document.getElementById("modalDevelopers"),
  modalEfficiency: document.getElementById("modalEfficiency"),
  modalError: document.getElementById("modalError"),
  modalSave: document.getElementById("modalSave"),
  modalCancel: document.getElementById("modalCancel"),
  modalClose: document.getElementById("modalClose"),
  sprintItemTemplate: document.getElementById("sprintItemTemplate"),
  taskRowTemplate: document.getElementById("taskRowTemplate"),
  // Tabs
  tabSprint: document.getElementById("tabSprint"),
  tabBacklog: document.getElementById("tabBacklog"),
  sprintView: document.getElementById("sprintView"),
  backlogView: document.getElementById("backlogView"),
  // Sprint task card — add-by-ID
  addByIdInput: document.getElementById("addByIdInput"),
  addByIdBtn: document.getElementById("addByIdBtn"),
  // Backlog panel (sprint view, drag-to-add)
  backlogPanel: document.getElementById("backlogPanel"),
  backlogPanelToggle: document.getElementById("backlogPanelToggle"),
  backlogPanelRows: document.getElementById("backlogPanelRows"),
  backlogPanelRowTemplate: document.getElementById("backlogPanelRowTemplate"),
  // Backlog view
  backlogExpandAllBtn: document.getElementById("backlogExpandAllBtn"),
  backlogCollapseAllBtn: document.getElementById("backlogCollapseAllBtn"),
  backlogAddStoryBtn: document.getElementById("backlogAddStoryBtn"),
  backlogImportCsvBtn: document.getElementById("backlogImportCsvBtn"),
  backlogExportCsvBtn: document.getElementById("backlogExportCsvBtn"),
  backlogDeleteAllBtn: document.getElementById("backlogDeleteAllBtn"),
  backlogImportFile: document.getElementById("backlogImportFile"),
  backlogTableBody: document.getElementById("backlogTableBody"),
  backlogStoryRowTemplate: document.getElementById("backlogStoryRowTemplate"),
  backlogTaskRowTemplate: document.getElementById("backlogTaskRowTemplate"),
  // Backlog "Clear All" confirm dialog
  confirmDeleteBacklogModal: document.getElementById("confirmDeleteBacklogModal"),
  confirmDeleteBacklogCancel: document.getElementById("confirmDeleteBacklogCancel"),
  confirmDeleteBacklogConfirm: document.getElementById("confirmDeleteBacklogConfirm"),
  // Task remove confirm dialog
  confirmRemoveTaskModal: document.getElementById("confirmRemoveTaskModal"),
  confirmRemoveTaskName: document.getElementById("confirmRemoveTaskName"),
  confirmRemoveTaskCancel: document.getElementById("confirmRemoveTaskCancel"),
  confirmRemoveTaskConfirm: document.getElementById("confirmRemoveTaskConfirm"),
};
