export const dom = {
  sprintList: document.getElementById("sprintList"),
  newSprintBtn: document.getElementById("newSprintBtn"),
  deleteSprintBtn: document.getElementById("deleteSprintBtn"),
  sprintName: document.getElementById("sprintName"),
  startDate: document.getElementById("startDate"),
  endDate: document.getElementById("endDate"),
  developers: document.getElementById("developers"),
  efficiency: document.getElementById("efficiency"),
  addTaskBtn: document.getElementById("addTaskBtn"),
  taskRows: document.getElementById("taskRows"),
  totalPoints: document.getElementById("totalPoints"),
  remainingPoints: document.getElementById("remainingPoints"),
  workingDays: document.getElementById("workingDays"),
  doneTasks: document.getElementById("doneTasks"),
  manDays: document.getElementById("manDays"),
  effectiveManDays: document.getElementById("effectiveManDays"),
  idealBurn: document.getElementById("idealBurn"),
  availableDays: document.getElementById("availableDays"),
  availableDaysValue: document.getElementById("availableDaysValue"),
  chart: document.getElementById("burndownChart"),
  showDayNumbers: document.getElementById("showDayNumbers"),
  exportBtn: document.getElementById("exportBtn"),
  importBtn: document.getElementById("importBtn"),
  importFile: document.getElementById("importFile"),
  sprintItemTemplate: document.getElementById("sprintItemTemplate"),
  taskRowTemplate: document.getElementById("taskRowTemplate"),
};
